spring:
  application:
    name: graalvmnativeimagejdbcdriver

  # Datasource Configuration
  datasource:
    url: jdbc:oracle:thin:@ATP110513_tp?TNS_ADMIN=/home/LL110513_U/myatpwallet
    username: ADMIN
    password: ATP110513
    driver-class-name: oracle.jdbc.OracleDriver
    type: oracle.ucp.jdbc.PoolDataSource
    oracleucp:
      connection-factory-class-name: oracle.jdbc.pool.OracleDataSource
      connection-pool-name: ConnectionPool
      initial-pool-size: 15
      min-pool-size: 10
      max-pool-size: 30